### ISSUE TITLE
branch names with a slash are truncates

### ISSUE THREAD

**Issue by nmn** [olmokramer/atom-tree-view-git-branch#1]
Branch names which a have a slash in their name, don't show up correctly.

For example, instead of `release/v5.0` I just see `v5.0`

**Comment by olmokramer** [comment]
Thanks for reporting the issue! I didn't realise people would use branch names with a slash in them. I'll try to fix this right now :)

**Comment by olmokramer** [comment]
I just published v0.0.2 that should fix this. Please let me know if it works

**Comment by nmn** [comment]
Thanks, it seems to work. (check out git-flow it recommends slashes in branch names for different types of branches)
