### ISSUE TITLE
Does not work in atom 1.19

### ISSUE THREAD

**Issue by mrleblanc101** [olmokramer/atom-tree-view-git-branch#18]
Hi,
I don't know if the plugin is still supported but it doesn't work in Atom 1.19

**Comment by aleclofabbro** [comment]
Same for me with Atom 1.19.2 x64

**Comment by camlafit** [comment]
same pb with last 1.21

looks installed but in explorer no branches switcher view

**Comment by budcodem** [comment]
Version 1.22.1 x64 here .. doesn't work either....

**Comment by yubaoquan** [comment]
Hi guys, try this one [tree-view-git-branch-fix](https://atom.io/packages/tree-view-git-branch-fix)

**Comment by camlafit** [comment]
Hello

Great looks better but with some bugs again :)
