### ISSUE TITLE
I don't see anything

### ISSUE THREAD

**Issue by wolftune** [olmokramer/atom-tree-view-git-branch#2]
I installed this, but I don't see anything at all, no commands, no options, no way to turn it on. I don't see the git branches as shown in the screenshot…

**Comment by olmokramer** [comment]
Hmm, that's weird. If you open the DevTools console (<kbd>ctrl-shift-i</kbd> and then go to the console tab at the top of the window), does it log an error? If it does, could you post the error here?

**Comment by wolftune** [comment]
sorry, no error there. To be specific, I'm on GNU/Linux. I try going to the command things to toggle this and nothing happens at all.

**Comment by mxmrlt** [comment]
Same here with this error in the console...
(Windows 10 + Atom 1.0.11)

Cannot read property 'classList' of null TypeError: Cannot read property 'classList' of null
  at getProjectRootEl (C:\Users\raultm.atom\packages\tree-view-git-branch\lib\main.js:62:13)
  at C:\Users\raultm.atom\packages\tree-view-git-branch\lib\main.js:51:29
  at process._tickCallback (node.js:367:9)
main.js:50 (anonymous function)node.js:367 _tickCallback

**Comment by jbehrends** [comment]
Same thing on OSX 10.10.5 and Atom 1.0.11

From Developer Console:
Cannot read property 'classList' of null TypeError: Cannot read property 'classList' of null
  at getProjectRootEl (/Users/myself/.atom/packages/tree-view-git-branch/lib/main.js:62:13)
  at /Users/myself/.atom/packages/tree-view-git-branch/lib/main.js:51:29
  at process._tickCallback (node.js:367:9)

**Comment by olmokramer** [comment]
Can you please run the following in the DevTools console? It should output the paths of all git repositories currently open in Atom (or "not a repository" if the project isn't a repository) and the element of that repository in the tree view. If it logs something else, how does it differ from the expected output?

``` js
atom.project.getRepositories().forEach(function(repo) {
  if(!repo) console.log("not a repository");
  else console.log(repo.getPath(), document.querySelector('.tree-view-resizer [data-path="' + repo.getPath() + '"]'));
});
```

**Comment by wolftune** [comment]
It says my path and .git but then null and undefined and something about VM601:4

**Comment by jbehrends** [comment]
I get:
/Users/myself/repos/mygitrepo/.git null
undefined

**Comment by olmokramer** [comment]
Aha, I think I know what the problem is. Is by any chance the `.git` folder from your repository hidden? Either because the project root folder is collapsed, or tree view's `hideVCSIgnoredFiles` option is enabled

**Comment by jbehrends** [comment]
So in my tree view, I do NOT see the .git folder. I can go into the shell cd to the folder just fine...
Looking at Atom -> Settings -> Core Settings:  I have .git listed under "Ignored Names"

**Comment by olmokramer** [comment]
Yep, that sounds about right. I just published a new version that should fix this issue. Please let me know if it works!

**Comment by wolftune** [comment]
Fixed!
