### ISSUE TITLE
Failed to load the tree-view-git-branch package

### ISSUE THREAD

**Issue by BlackSkorpio** [olmokramer/atom-tree-view-git-branch#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.13
**System**: Unknown Windows Version
**Thrown From**: [tree-view-git-branch](https://github.com/olmokramer/atom-tree-view-git-branch) package, v0.0.3
### Stack Trace

Failed to load the tree-view-git-branch package

```
At Cannot find module 'array.from'

Error: Cannot find module 'array.from'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Bjarne Varöystrand\AppData\Local\atom\app-1.0.13\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Bjarne Varöystrand\.atom\packages\tree-view-git-branch\lib\tree-view-git-branch-list.js:2:28)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Bjarne Varöystrand\AppData\Local\atom\app-1.0.13\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-coffee-script",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-less",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-shellscript",
      "language-sql",
      "language-toml",
      "welcome"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
branch-status, v0.8.1
file-type-icons, v0.7.3
file-types, v0.5.1
github-utils, v0.6.2
tree-view-git-branch, v0.0.3

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
That's weird... It's right there in [package.json](https://github.com/olmokramer/atom-tree-view-git-branch/blob/master/package.json#L18). How did you install the package?

**Comment by BlackSkorpio** [comment]
I installed via packages inside atom

**Comment by olmokramer** [comment]
If you `cd` into `~/.atom/packages/tree-view-git-branch/node_modules`, there should be a folder called `array.from`. Is it there? If not, try to run `apm install` from `~/.atom/packages/tree-view-git-branch` directory.

**Comment by BlackSkorpio** [comment]
It's there...

**Comment by olmokramer** [comment]
Is it all lowercase?

**Comment by BlackSkorpio** [comment]
That to.

**Comment by olmokramer** [comment]
Can you please try the following:
1. Completely close all instances of Atom (check your task manager to be sure)
2. Delete the directory `~/.atom/compile-cache`
3. Start Atom again

**Comment by olmokramer** [comment]
There is a [topic on discuss.atom.io](https://discuss.atom.io/t/atom-throwing-several-failed-to-load-the-xyz-package-errors/20969) that describes an issue that appears to be the same issue you're having. I'll watch it closely, but I thought you might want to as well :)

**Comment by BlackSkorpio** [comment]
Thnx for the link...
Will follow.

Deleting compile-cache did noting :/

**Comment by olmokramer** [comment]
I'm going to close this as it seems it is a problem in general with Atom. See https://github.com/atom/atom/issues/8891
